# Generated by Django 5.1 on 2024-09-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_email_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="social_type",
            field=models.CharField(
                choices=[
                    ("common", "Common"),
                    ("kakao", "Kakao"),
                    ("naver", "Naver"),
                    ("google", "Google"),
                ],
                default="common",
                max_length=20,
            ),
        ),
    ]
